# Generated by Django 3.0.2 on 2020-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_cat', models.CharField(default='property_type', max_length=20)),
                ('property_type', models.CharField(default='sell/rent', max_length=10)),
                ('project_name', models.CharField(max_length=20)),
                ('description', models.TextField(default=500)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='pages/images')),
                ('contact_PersonName', models.CharField(default='admin', max_length=20)),
                ('contact_Number', models.CharField(default='9999-999-999', max_length=12)),
                ('contact_email', models.EmailField(default='example123@emal.com', max_length=50)),
            ],
        ),
    ]
