# Generated by Django 3.0.2 on 2020-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_uploadproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperty',
            name='contact_Number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='uploadproperty',
            name='contact_PersonName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadproperty',
            name='contact_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadproperty',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uploadproperty',
            name='property_cat',
            field=models.CharField(choices=[('Home', 'Home'), ('Appartment', 'Appartment'), ('Building', 'Building'), ('Land', 'Land'), ('Farm House', 'Farm House'), ('Banglow', 'Banglow')], max_length=15),
        ),
        migrations.AlterField(
            model_name='uploadproperty',
            name='property_type',
            field=models.CharField(max_length=10),
        ),
    ]
